import { memo, useMemo, useState } from 'react';
import {
  BaseEdge,
  EdgeLabelRenderer,
  getBezierPath,
  Position,
  type EdgeProps,
} from '@xyflow/react';

import {
  CANVAS_NODE_TYPES,
  type CanvasEdgeData,
  type CanvasEdgeRelation,
} from '@/features/canvas/domain/canvasNodes';
import { useCanvasStore } from '@/stores/canvasStore';
import { useSettingsStore } from '@/stores/settingsStore';
import { buildOrthogonalRoute } from './edgeRouting';

const EDGE_RELATION_COLORS: Record<CanvasEdgeRelation, string> = {
  default: 'rgba(226,232,240,0.72)',
  'text-flow': 'rgba(96,165,250,0.88)',
  'image-flow': 'rgba(52,211,153,0.88)',
  'video-flow': 'rgba(249,115,22,0.88)',
  'audio-flow': 'rgba(236,72,153,0.88)',
  'storyboard-map': 'rgba(167,139,250,0.92)',
  'auto-generated': 'rgba(148,163,184,0.82)',
};

const EDGE_COLOR_CYCLE = [
  null,
  '#60a5fa',
  '#34d399',
  '#f59e0b',
  '#f472b6',
  '#a78bfa',
] as const;

export const DisconnectableEdge = memo(function DisconnectableEdge(props: EdgeProps) {
  const {
    id,
    source,
    target,
    selected,
    sourceX,
    sourceY,
    sourcePosition,
    targetX,
    targetY,
    targetPosition,
    markerEnd,
    style,
  } = props;
  const edgeData = (props.data ?? {}) as CanvasEdgeData;
  const [isHovered, setIsHovered] = useState(false);
  const deleteEdge = useCanvasStore((state) => state.deleteEdge);
  const updateEdgeData = useCanvasStore((state) => state.updateEdgeData);
  const nodes = useCanvasStore((state) => state.nodes);
  const selectedNodeId = useCanvasStore((state) => state.selectedNodeId);
  const hoveredNodeId = useCanvasStore((state) => state.hoveredNodeId);
  const canvasEdgeRoutingMode = useSettingsStore((state) => state.canvasEdgeRoutingMode);
  const routingMode = edgeData.routingStyle && edgeData.routingStyle !== 'inherit'
    ? edgeData.routingStyle === 'spline'
      ? 'spline'
      : 'orthogonal'
    : canvasEdgeRoutingMode;

  const { edgePath, labelX, labelY } = useMemo(() => {
    if (routingMode === 'spline') {
      const [path, nextLabelX, nextLabelY] = getBezierPath({
        sourceX,
        sourceY,
        sourcePosition,
        targetX,
        targetY,
        targetPosition,
      });
      return {
        edgePath: path,
        labelX: nextLabelX,
        labelY: nextLabelY,
      };
    }

    const route = buildOrthogonalRoute({
      sourceId: source,
      targetId: target,
      sourceX,
      sourceY,
      sourcePosition: sourcePosition ?? Position.Right,
      targetX,
      targetY,
      targetPosition: targetPosition ?? Position.Left,
      nodes,
      smartAvoidance: routingMode === 'smartOrthogonal',
    });
    return {
      edgePath: route.path,
      labelX: route.labelX,
      labelY: route.labelY,
    };
  }, [
    nodes,
    routingMode,
    source,
    sourcePosition,
    sourceX,
    sourceY,
    target,
    targetPosition,
    targetX,
    targetY,
  ]);

  const isProcessingEdge = useMemo(() => {
    const sourceNode = nodes.find((node) => node.id === source);
    const targetNode = nodes.find((node) => node.id === target);

    if (!sourceNode || !targetNode || targetNode.type !== CANVAS_NODE_TYPES.exportImage) {
      return false;
    }

    const isSupportedSource =
      sourceNode.type === CANVAS_NODE_TYPES.storyboardGen ||
      sourceNode.type === CANVAS_NODE_TYPES.imageEdit;
    if (!isSupportedSource) {
      return false;
    }

    return (targetNode.data as { isGenerating?: boolean } | undefined)?.isGenerating === true;
  }, [nodes, source, target]);

  const relation = edgeData.autoGenerated
    ? (edgeData.relation === 'storyboard-map' ? 'storyboard-map' : 'auto-generated')
    : (edgeData.relation ?? 'default');
  const relationColor = edgeData.color ?? EDGE_RELATION_COLORS[relation];
  const isDashed = edgeData.lineStyle === 'dashed' || relation === 'storyboard-map';
  const processingStroke = 'rgb(var(--accent-rgb) / 0.94)';
  const processingDashStroke = 'rgb(var(--accent-rgb) / 1)';
  const baseStrokeWidth = isProcessingEdge
    ? (selected ? 2.7 : 2.2)
    : (selected ? 2.4 : 1.9);
  const isRelatedToFocusedNode =
    Boolean(selectedNodeId && (source === selectedNodeId || target === selectedNodeId))
    || Boolean(hoveredNodeId && (source === hoveredNodeId || target === hoveredNodeId));
  const visualOpacity = selected || isHovered
    ? 1
    : isRelatedToFocusedNode
      ? 0.82
      : 0.14;
  const visualStrokeWidth = selected || isHovered
    ? baseStrokeWidth + 0.5
    : isRelatedToFocusedNode
      ? baseStrokeWidth + 0.15
      : Math.max(1.1, baseStrokeWidth - 0.35);
  const hitStrokeWidth = Math.max(16, baseStrokeWidth * 5);

  return (
    <>
      {isProcessingEdge && (
        <path
          d={edgePath}
          fill="none"
          stroke={processingDashStroke}
          strokeWidth={selected ? 2.5 : 2.1}
          strokeLinecap="round"
          strokeDasharray="8 10"
          className="canvas-processing-edge__flow"
          style={{ pointerEvents: 'none' }}
        />
      )}
      <BaseEdge
        id={id}
        path={edgePath}
        markerEnd={markerEnd}
        style={{
          stroke: isProcessingEdge ? processingStroke : (style?.stroke ?? relationColor),
          strokeWidth: visualStrokeWidth,
          strokeDasharray: isDashed ? '8 8' : undefined,
          opacity: visualOpacity,
          transition: 'opacity 120ms ease, stroke 120ms ease, stroke-width 120ms ease',
          ...style,
        }}
      />
      <path
        d={edgePath}
        fill="none"
        stroke="transparent"
        strokeWidth={hitStrokeWidth}
        style={{ cursor: 'pointer' }}
        onMouseEnter={() => setIsHovered(true)}
        onMouseLeave={() => setIsHovered(false)}
      />
      {(selected || isHovered || isRelatedToFocusedNode) && (
        <EdgeLabelRenderer>
          <div
            className="nodrag nopan absolute flex items-center gap-1 rounded-full border border-[var(--ui-border-soft)] bg-[var(--ui-surface-panel)] px-1 py-1 text-text-muted shadow-lg"
            style={{
              transform: `translate(-50%, -50%) translate(${labelX}px, ${labelY}px)`,
              pointerEvents: 'all',
            }}
          >
            <button
              type="button"
              className="flex h-6 min-w-6 items-center justify-center rounded-full px-1 text-[10px] font-medium transition-colors hover:bg-[var(--ui-hover-surface)] hover:text-text-dark"
              onClick={(event) => {
                event.stopPropagation();
                updateEdgeData(id, { lineStyle: isDashed ? 'solid' : 'dashed' });
              }}
              title="Toggle line style"
              aria-label="Toggle line style"
            >
              {isDashed ? 'D' : 'S'}
            </button>
            <button
              type="button"
              className="flex h-6 min-w-6 items-center justify-center rounded-full px-1 text-[10px] font-medium transition-colors hover:bg-[var(--ui-hover-surface)] hover:text-text-dark"
              onClick={(event) => {
                event.stopPropagation();
                const currentIndex = EDGE_COLOR_CYCLE.findIndex(
                  (item) => item === (edgeData.color ?? null)
                );
                const nextColor =
                  EDGE_COLOR_CYCLE[(currentIndex + 1 + EDGE_COLOR_CYCLE.length) % EDGE_COLOR_CYCLE.length];
                updateEdgeData(id, { color: nextColor });
              }}
              title="Cycle edge color"
              aria-label="Cycle edge color"
            >
              C
            </button>
            <button
              type="button"
              className="flex h-6 min-w-6 items-center justify-center rounded-full px-1 text-[10px] font-medium transition-colors hover:bg-[var(--ui-hover-surface)] hover:text-text-dark"
              onClick={(event) => {
                event.stopPropagation();
                updateEdgeData(id, {
                  routingStyle:
                    edgeData.routingStyle === 'spline'
                      ? 'orthogonal'
                      : edgeData.routingStyle === 'orthogonal'
                        ? 'inherit'
                        : 'spline',
                });
              }}
              title="Cycle edge routing"
              aria-label="Cycle edge routing"
            >
              R
            </button>
            <button
              type="button"
              className="flex h-6 w-6 items-center justify-center rounded-full transition-colors hover:bg-white/10 hover:text-text-dark"
              onClick={(event) => {
                event.stopPropagation();
                deleteEdge(id);
              }}
              aria-label="Delete edge"
              title="Delete edge"
            >
              <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24">
                <path
                  fill="currentColor"
                  fillRule="evenodd"
                  d="M2 12C2 6.477 6.477 2 12 2s10 4.477 10 10s-4.477 10-10 10S2 17.523 2 12m7.707-3.707a1 1 0 0 0-1.414 1.414L10.586 12l-2.293 2.293a1 1 0 1 0 1.414 1.414L12 13.414l2.293 2.293a1 1 0 0 0 1.414-1.414L13.414 12l2.293-2.293a1 1 0 0 0-1.414-1.414L12 10.586z"
                  clipRule="evenodd"
                />
              </svg>
            </button>
          </div>
        </EdgeLabelRenderer>
      )}
    </>
  );
});
